version: "3.9"
services:
  flask_app:
    init: true
    env_file:
      - ./.env
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:${FLASK_PORT}:${FLASK_PORT}
